server:
  port: 8001
spring:
  application:
    name: api-products
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mlt-api-products:southamerica-west1:mlt-products
    username: root
    password: mlt-api-products
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace